[client]
showErrorDetails = false
toolbarMode = "minimal"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8080

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
